import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div>
        <nav className="bg-gray-600">
          <Link href = "/login"> 로그인 </Link>
          {/* <h1>아래 로그인</h1>
          <ui>
            <li><Link href="http://localhost:8080/oauth2/initiate?intent=login&provider=naver">naver</Link></li>
            <li><Link href="http://localhost:8080/oauth2/initiate?intent=login&provider=google">google</Link></li>
            <li><Link href="http://localhost:8080/oauth2/initiate?intent=login&provider=kakao">kakao</Link></li>
          </ui>

          <h1>아래 회원가입</h1>      
          <ui>
            <li><Link href="http://localhost:8080/oauth2/initiate?intent=signup&provider=naver">naver</Link></li>
            <li><Link href="http://localhost:8080/oauth2/initiate?intent=signup&provider=google">google</Link></li>
            <li><Link href="http://localhost:8080/oauth2/initiate?intent=signup&provider=kakao">kakao</Link></li>
          </ui> */}
      </nav>
        {children}
      </div>
  );
}
